services:
  - type: web
    name: bm
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    previews:
      generation: automatic
    domains:
      - bm.taskratchet.com
